### ISSUE TITLE
Breaks down if receiving a second call

### ISSUE THREAD

**Issue by WildS0ft** [harv/XRecorder#6]
It doesn't handle receiving a second call at all when already in one. Reacts differently depending on the users action.

For example: If you get another call during an ongoing call and no action is taken, it stops recording then starts again. Naming the newer file after the ignored call.

Answering or actively ignoring the second call stops the recording.

**Device:** Sony Z1 Compact (D5503)
**Android:** 5.1.1
**Version:** 14.6.A.1.236
**Xposed Framework:** 82
**com.sonymobile.callrecording:** 1.0.A.0.8

**Comment by harv** [comment]
Thanks for your report!
This bug is fixed in last commit 183038d.

The recording will not ended in 2 situations:
1. reject secondary call
2. hangup primary call then answer  secondary call

but will ended if you
1. hold primary call then answer  secondary call, then hangup one
