### ISSUE TITLE
Recordings longer than 30 minutes breaks the module

### ISSUE THREAD

**Issue by WildS0ft** [harv/XRecorder#7]
After 30 minutes the recording is stopped and saved. After the call ends the recording starts back up again. Sometimes you aren't able to stop it and sometimes you are. Regardless the **module is now completely broken until the device restarts.**

I get that the 30 minutes is a limit with the CallRecording app itself. But this mod should at the very least be able to automatically start recording to a new file if the conversation exceeds the limit. For example adding the prefix _(2)_ at the end of the new filename.

**Device:** Sony Z1 Compact (D5503)
**Android:** 5.1.1
**Version:** 14.6.A.1.236
**Xposed Framework:** 82
**com.sonymobile.callrecording:** 1.0.A.0.8

**Comment by harv** [comment]
The reason is same to #6.

Since the recording will not start if there is no call alive, this bug may not reproduced.
